### ISSUE TITLE
[auto-test] Test cases refactoring

### ISSUE THREAD

**Issue by lignay** [matrixorigin/mysql-tester#2]
In v0.1.0, MatrixOne supports below features:

**DDL** 
1. CREATE / DROP DATABASE: _Done_[9]
2. CREATE / DROP TABLE: _Done_[19]

**DML**

1. INSERT: _Done_[4]
2. LOAD DATA: _In Progress_
3. SELECT: 
- WHERE: _Done_
- GROUP BY: _Done_[11]
- ORDER BY:  _Done_[10]
- LIMIT, OFFSET: _Done_ [3]
- HAVING: _Not supported_
- USING: _Not supported_
4. SHOW: 

- DATABASES: _Done_[]
- TABLES: _Done_[]
- CREATE TABLE: _Not supported_
- CREATE DATABASE: _Not supported_
- COLUMNS: _Not supported_

5. EXPLAIN: _Not supported_
6. USE:  _Done_[]

**Data Type**

1. TINYINT / SMALLINT / INT / BIGINT, SIGNED / UNSIGNED : _Done[2]_
2. FLOAT / DOUBLE : _Done [3]_
3. CHAR / VARCHAR: _Done[1]_
4. DATE / DATETIME: _Not supported_

**Operators**

1. `>, >=, <, <=, <>, !=, =`: _In progress_
2. BETWEEN … AND …, NOT BETWEEN … AND … : _In progress_
3. AND, &&, NOT, !, OR, || : _Done_
4. +, -, *, /, %, MOD, DIV, NEG : _Done_
5. CAST : _Done_

**Aggregation Function**: _DONE_ [12]
1. COUNT
2. SUM
3. AVG
4. MAX
5. MIN

**Comment by domingozhang** [comment]
DDL

CREATE / DROP DATABASE_: Done_
CREATE / DROP TABLE_: Done_

DML

INSERT_: Done_
_LOAD DATA_: In Progress

Data Type

TINYINT / SMALLINT / INT / BIGINT, SIGNED / UNSIGNED_: In Progress_
FLOAT / DOUBLE_: Done_
CHAR / VARCHAR_: In Progress_

**Comment by anitajjx** [comment]
DML

WHERE: In-progress

Operators

AND, &&, NOT, !, OR, || :In-progress
+, -, *, /, %, MOD, DIV, NEG : In-progress
CAST: In-progress

**Comment by lignay** [comment]
All tasks have been done. Close this ticket.
